POST http://localhost:8080/car/create/
Content-Type: application/json

{
  "licencePlate": "ABC-123-DEF",
  "model": "Ford Anglia",
  "year": 1993

}

###
POST http://localhost:8080/car/create/
Content-Type: application/json

{
  "licencePlate": "ZYX-987-WVU",
  "model": "Ford Mustang",
  "year": 1999

}

