POST http://localhost:8080/part/create/
Content-Type: application/json

{
    "name": "carburateur",
    "price": "111,11",
    "quantity": "17"
}

###
POST http://localhost:8080/part/create/
Content-Type: application/json

{
  "name": "uitlaat",
  "price": "501,99",
  "quantity": "9"
}

###
POST http://localhost:8080/part/create/
Content-Type: application/json

{
  "name": "wieldop",
  "price": "100,99",
  "quantity": "16"
}