POST http://localhost:8080/customer/create/
Content-Type: application/json

{
  "firstName": "Harry",
  "lastName": "Potter",
  "address": "Cupboard under the stairs",
  "email": "thechosenone@gmail.com"
}

###
POST http://localhost:8080/customer/create/
Content-Type: application/json

{
  "firstName": "Jack",
  "lastName": "Frost",
  "address": "Some lake idk",
  "email": "jackfrost@gmail.com"
}



